### ISSUE TITLE
UI element to run Stemweb

### ISSUE THREAD

**Issue by jorisvanzundert** [tla/stemmaweb#149]

**Comment by jorisvanzundert** [comment]
This one needs a tad bit more info:

* Do the HIIT/EADH logos and message need to be transfered?
* Starting a job seems easy enough, but how is the status communicated, what does the user see where?

**Comment by tla** [comment]
- Yes, they should be transferred I think.
- When the job finishes, the Stemweb server will asynchronously send the results back to the Stemmaweb server and the new stemma will be saved with the tradition. (I need to check what happens if an error is returned.) How this gets communicated to the user is a design decision; it is possible for the user to send a request to check progress (to make sure it's still running), but if the user went to have coffee in the meantime and reloads the page, maybe the stemma should just be there. Or maybe if a job has completed, the user should get an alert next time they reload. What do you think is best?

**Comment by jorisvanzundert** [comment]
Re jobs: I'd like a jobs panel at the bottom of the right hand side properties/menu bar which lists any job with 'running' or 'ready' or 'error', and a user can delete ready ones. An error message for a job could be a fold down for that job in the same panel. Obviously the panel would only be there *if* there are jobs.
