### ISSUE TITLE
Switch backend from Node to Flask

### ISSUE THREAD

**Issue by tla** [tla/stemmaweb#94]

**Comment by tla** [comment]
### Endpoints

The Flask backend needs to have the following endpoints / handle the following tasks:

- `/login`: Log in the user, either through Google OAuth or through email/password stored in Stemmarest.
- `/register`: Register a new user via email/password. Currently we use Captcha for this and should continue.
- `/api`: Check permissions (see below) and either deny or pass through the rest of the URL to the Stemmarest endpoint (presumably set via environment variable, but I'm open to other solutions), paying attention to expected and received Content-Type settings, and pass the answer back to the front end. 

### Authorisation

The current auth model in Stemmaweb is that a tradition is owned by a single user, and that tradition can be set to public or private. Also, a user can be a normal user or an admin user. Thus:

- Admin users: have read/write access to all traditions
- Users: read/write access to their traditions, read-only access to public ones
- Not logged in: read-only access to public traditions

Eventually we might like to have a model that allows collaboration, but that is out of scope of this issue.

### API parameters

The vast majority of the API endpoints take query or post parameters, and return a JSON response. You should be able to assume that the correct request form (query/post, content-type, etc.) was made correctly by the client. Some endpoints need complicated things like file upload; again this should be formatted correctly by the client but also needs to be handled correctly on passthrough. See https://dhuniwien.github.io/tradition_repo/ for the backend API documentation.

**Comment by peter-gy** [comment]
Since we are transitioning from a Node backend to Python, are we also migrating the `ejs` templates to `Jinja2 `? Also, given that we eliminate all the javascript code needed for the backend, is it ok if I refactor the repo structure so that the python dependencies and node dependencies are isolated nicely? I would keep only the dockerfiles, the markdown docs as well as the utility scripts in the root.

**Comment by tla** [comment]
Templates: yes feel free to migrate them - in fact, I'm not sure we have any actual templating in them so far. So this may be exceptionally easy. Just make sure that there is at least a working `/api` endpoint and that @jorisvanzundert knows when you push that change.

Refactoring: fine. I'm not sure we will have any node dependencies at all if we are not using express. @jorisvanzundert can also correct me if I'm wrong.

**Comment by peter-gy** [comment]
I agree, migrating the templates should be mostly copy-pasting code, as `<%= title %>` is the only actively used template variable.

The `package.json` lists some client-side dependencies too:

```json
{
...
    "d3": "^7.2.1",
    "d3-graphviz": "^4.0.0",
   ...
}
```

However, as far as I saw, the required js files are also committed to the repo directly under `public/js`.

**Comment by peter-gy** [comment]
### Related Task

#### Migrate and modularize the frontend

- Using a build tool is ok as long as:
  - we do not rely on custom build logic
  - we can produce source maps for the whole output so that our work is transparent & observable for everyone
- To keep things slim, we do not use TypeScript. We can provide type-inference to JS code using [JSDoc](https://jsdoc.app/)
- The code should not be declared in a single monolithic file, we should have a modular JS app
